name: Print Info

on:
    push:
        paths:
            - students_note.md

jobs:
    build:
        runs-on : ubuntu-latest
    
        env:
            Repo_Name: ${{github.repository}}
            S_username : ${{github.actor}}

        steps:
            - name: Print repository name
              run: |
               echo "Repository: $Repo_Name"
               echo "Student Username: $S_username"